### ISSUE TITLE
Add flags for the states and territories of Australia

### ISSUE THREAD

**Issue by RudeySH** [kent1D/svg-flags#3]
See [Wikipedia](https://en.wikipedia.org/wiki/States_and_territories_of_Australia) for more details.

**Comment by kent1D** [comment]
Should be fixed by https://github.com/kent1D/svg-flags/commit/cbd82b1f98fed113de0764174237288ae2b754f0

Please tell me if you don't agree

**Comment by RudeySH** [comment]
It appears to be complete. Thanks!
