### ISSUE TITLE
Missing provinces of France

### ISSUE THREAD

**Issue by RudeySH** [kent1D/svg-flags#4]
I noticed this repository includes the flags of [Brittany](https://en.wikipedia.org/wiki/Brittany) and [Corsica](https://en.wikipedia.org/wiki/Corsica). The rest of the [provinces of France](https://en.wikipedia.org/wiki/Provinces_of_France) should be added.

**Comment by kent1D** [comment]
Should be fixed by a4c122b1321c6916f67a2f6c2f90f5b4dc4604e4
